In [6]:
#1 Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to
# compute the mean and variance of the elements present in the array.
import numpy as np
def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

# Example usage:
N = 5  # Number of dimensions
vector = np.random.rand(N)  # Generating a random feature vector of size N
print("Vector:",vector)
mean, variance = compute_mean_and_variance(vector)
print("Mean:", mean)
print("Variance:", variance)

Vector:{:.2f} [0.74013704 0.141731   0.77005797 0.19994571 0.752625  ]
Mean:{:.2f} 0.5208993464188436
Variance:{:.2f} 0.08212436639440979


In [3]:
#2 Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to
# compute the Covariance between them.

import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.cov(vector1, vector2, bias=True)[0][1]
    return covariance

# Example usage:
M = 5  # Number of dimensions
N = 100  # Number of samples
# Generating two random feature vectors of size M
vector1 = np.random.rand(1, M)
vector2 = np.random.rand(1, M)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
covariance = compute_covariance(vector1, vector2)
print("Covariance:", covariance)

Vector 1: [[0.96828304 0.74395394 0.41152266 0.62103609 0.60088797]]
Vector 2: [[0.00565574 0.46514767 0.24471006 0.72164471 0.99238242]]
Covariance: -0.025797655420221045


In [4]:
#3 Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

import numpy as np

def compute_correlation(vector1, vector2):
    correlation = np.corrcoef(vector1, vector2)[0, 1]
    return correlation

# Example usage:
N = 5  # Number of dimensions
vector1 = np.random.rand(N)  # Generating a random vector of size N
vector2 = np.random.rand(N)  # Generating another random vector of size N
print("Vector 1:", vector1)
print("Vector 2:", vector2)
correlation = compute_correlation(vector1, vector2)
print("Correlation:", correlation)

Vector 1: [0.2556255  0.40488593 0.73015911 0.87891268 0.25358218]
Vector 2: [0.81259439 0.4572168  0.5888209  0.10524009 0.20101215]
Correlation: -0.38477514762527837


In [7]:
#4 Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th
#entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and
#correlation matrix.

import numpy as np

def compute_covariance_matrix(feature_matrix):
    covariance_matrix = np.cov(feature_matrix)
    return covariance_matrix

def compute_correlation_matrix(feature_matrix):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix

# Example usage:
M = 3  # Number of dimensions/features
N = 5  # Number of samples
feature_matrix = np.random.rand(M, N)  # Generating a random feature matrix of size MxN
print("Feature matrix:")
print(feature_matrix)
covariance_matrix = compute_covariance_matrix(feature_matrix)
print("\nCovariance matrix:")
print(covariance_matrix)
correlation_matrix = compute_correlation_matrix(feature_matrix)
print("\nCorrelation matrix:")
print(correlation_matrix)

Feature matrix:
[[0.96306432 0.27531914 0.96001998 0.42293299 0.85873124]
 [0.6124393  0.66197521 0.79024432 0.96495837 0.00147996]
 [0.07999097 0.64720465 0.28371629 0.79923399 0.8500426 ]]

Covariance matrix:
[[ 0.10476233 -0.04239445 -0.06398727]
 [-0.04239445  0.132854   -0.03463604]
 [-0.06398727 -0.03463604  0.11294854]]

Correlation matrix:
[[ 1.         -0.35935122 -0.58823472]
 [-0.35935122  1.         -0.28274871]
 [-0.58823472 -0.28274871  1.        ]]
